(function(){
  const D=window.POS_DATA, $=s=>document.querySelector(s); let lang=localStorage.getItem('pos-language')||'en'; let current=localStorage.getItem('pos-current')||'nouns';
  let progress=JSON.parse(localStorage.getItem('pos-progress')||'{}'), practiceChoice=null, quizIndex=0,quizAnswers=[];
  const tr=k=>D.ui[lang][k]||D.ui.en[k]||k, tx=o=>o[lang]||o.en;
  function save(){localStorage.setItem('pos-progress',JSON.stringify(progress));localStorage.setItem('pos-current',current)}
  function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.88;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='en-US'&&/Natural|Samantha|Google US English/i.test(v.name))||voices.find(v=>v.lang==='en-US')||null;speechSynthesis.speak(u)}
  function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
  function setLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('#language').value=lang;$('#homeLink').textContent=tr('home');$('#progressLabel').textContent=tr('progress');$('#resetBtn').textContent=tr('reset');$('#intro').textContent=lang==='es'?'Aprende cómo funcionan las palabras en inglés, un módulo práctico a la vez.':lang==='ar'?'تعلّم كيف تعمل الكلمات الإنجليزية، وحدة عملية في كل مرة.':'Learn how English words work—one practical module at a time.'}
  function nav(){const n=$('#moduleNav');n.innerHTML=D.modules.map(m=>`<button class="module-btn ${m.id===current?'active':''} ${progress[m.id]?.completed?'done':''}" data-id="${m.id}" type="button"><b>${m.icon}</b>${tx(m.title)}<span>${progress[m.id]?.score!=null?tr('score')+': '+progress[m.id].score+'/5':'0 / 5'}</span></button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=b.dataset.id;practiceChoice=null;quizIndex=0;quizAnswers=[];save();render();$('#lesson').focus()})}
  function updateOverall(){const done=D.modules.filter(m=>progress[m.id]?.completed).length,p=Math.round(done/D.modules.length*100);$('#overallText').textContent=p+'%';$('#overallBar').style.width=p+'%'}
  function translated(v){return lang==='es'?v.ses:lang==='ar'?v.sar:v.s}
  function render(){setLang();nav();updateOverall();const m=D.modules.find(x=>x.id===current);$('#lesson').innerHTML=`
    <header class="lesson-head"><div><p class="eyebrow">${tr('learn')} · ${tx(m.title)}</p><h2>${tx(m.title)}</h2><p class="definition">${tx(m.definition)}</p></div><div class="lesson-mark" aria-hidden="true">${m.icon}</div></header><p class="tip">💡 ${tx(m.tip)}</p>
    <section class="section"><h3 class="section-title"><span>1</span>${lang==='es'?'Categorías importantes':lang==='ar'?'الفئات المهمة':'Important categories'}</h3><div class="category-grid">${m.categories.map(c=>`<article class="category"><div class="emoji" aria-hidden="true">${c.emoji}</div><h3>${tx(c.name)}</h3><p dir="ltr">${c.words}</p></article>`).join('')}</div></section>
    <section class="section"><h3 class="section-title"><span>2</span>${lang==='es'?'Palabras en la vida real':lang==='ar'?'كلمات من الحياة اليومية':'Words in real life'}</h3><div class="vocab-grid">${m.vocab.map((v,i)=>`<article class="vocab"><div class="visual" role="img" aria-label="${v.w}">${v.emoji}</div><div class="vocab-body"><div class="word-line"><div><h3 dir="ltr">${v.w}</h3><div class="ipa">${v.ipa}</div></div><button class="audio" data-speak="${v.w}" aria-label="${tr('listen')}: ${v.w}">🔊</button></div><p class="translations">🇪🇸 ${v.es}<br>🇸🇦 ${v.ar}</p><p class="example" dir="ltr">${v.s}</p><p class="translated">${translated(v)}</p></div></article>`).join('')}</div></section>
    <section class="section"><h3 class="section-title"><span>3</span>${tr('practice')}</h3><div id="practice" class="activity"><p class="prompt">${tx(m.practice.prompt)}</p><div class="choices">${m.practice.options.map(o=>`<button class="choice" data-value="${o}" type="button">${o}</button>`).join('')}</div><p id="practiceFeedback" class="feedback" aria-live="polite"></p><div class="actions"><button id="practiceCheck" class="btn primary" type="button">${tr('check')}</button></div></div></section>
    <section class="section"><h3 class="section-title"><span>4</span>${tr('quiz')} · 5</h3><div id="quiz" class="quiz-card"></div></section>`;
    document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));document.querySelectorAll('#practice .choice').forEach(b=>b.onclick=()=>{practiceChoice=b.dataset.value;document.querySelectorAll('#practice .choice').forEach(x=>x.classList.toggle('selected',x===b))});$('#practiceCheck').onclick=checkPractice;renderQuiz();
  }
  function checkPractice(){const m=D.modules.find(x=>x.id===current),f=$('#practiceFeedback');if(!practiceChoice){f.textContent=tr('choose');f.className='feedback bad';return}const ok=practiceChoice===m.practice.answer;document.querySelectorAll('#practice .choice').forEach(b=>{b.classList.toggle('correct',b.dataset.value===m.practice.answer);b.classList.toggle('wrong',b.dataset.value===practiceChoice&&!ok)});f.textContent=(ok?tr('correct')+' ':tr('incorrect')+' ')+tx(m.practice.why);f.className='feedback '+(ok?'good':'bad')}
  function renderQuiz(){const m=D.modules.find(x=>x.id===current),box=$('#quiz');if(quizIndex>=m.quiz.length){const score=quizAnswers.filter((a,i)=>a===m.quiz[i].answer).length;const old=progress[current]?.score||0;progress[current]={completed:true,score:Math.max(score,old)};save();nav();updateOverall();box.innerHTML=`<div class="result"><p>${tr('complete')}</p><strong>${score}/5</strong><div class="actions" style="justify-content:center"><button id="reviewQuiz" class="btn secondary">${tr('review')}</button><button id="retryQuiz" class="btn primary">${tr('tryAgain')}</button><button id="nextModule" class="btn secondary">${current==='adverbs'?tr('menu'):tr('next')} →</button></div><div id="reviewList" class="review-list"></div></div>`;$('#retryQuiz').onclick=()=>{quizIndex=0;quizAnswers=[];renderQuiz()};$('#reviewQuiz').onclick=()=>{$('#reviewList').innerHTML=m.quiz.map((q,i)=>`<div class="review-item">${quizAnswers[i]===q.answer?'✓':'✕'} ${q.text}<br><small>${lang==='es'?'Respuesta':lang==='ar'?'الإجابة':'Answer'}: <b>${q.answer}</b></small></div>`).join('')};$('#nextModule').onclick=()=>{const i=D.modules.findIndex(x=>x.id===current);current=D.modules[(i+1)%D.modules.length].id;quizIndex=0;quizAnswers=[];render();$('#lesson').focus()};return}
    const q=m.quiz[quizIndex];box.innerHTML=`<div class="quiz-head"><h3>${q.text}</h3><span class="quiz-count">${quizIndex+1} / 5</span></div><div class="choices">${q.options.map(o=>`<button class="choice" data-answer="${o}" type="button">${o}</button>`).join('')}</div><p class="feedback" id="quizFeedback" aria-live="polite"></p>`;box.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{quizAnswers[quizIndex]=b.dataset.answer;box.querySelectorAll('.choice').forEach(x=>x.classList.toggle('selected',x===b));const ok=b.dataset.answer===q.answer;b.classList.add(ok?'correct':'wrong');if(!ok)box.querySelector(`[data-answer="${CSS.escape(q.answer)}"]`).classList.add('correct');$('#quizFeedback').textContent=ok?tr('correct'):tr('incorrect');$('#quizFeedback').className='feedback '+(ok?'good':'bad');box.querySelectorAll('.choice').forEach(x=>x.disabled=true);setTimeout(()=>{quizIndex++;renderQuiz()},850)})
  }
  $('#language').onchange=e=>{lang=e.target.value;localStorage.setItem('pos-language',lang);render()};$('#resetBtn').onclick=()=>{if(confirm(tr('resetAsk'))){progress={};save();render();toast(tr('reset'))}};render();
})();
