(()=>{'use strict';
const C=window.VerbCore,$=id=>document.getElementById(id),SAVE_KEY='verbQuestSavedGameV3';
let state=null,timerId=null,timeLeft=0,selectedTile=null,answerLocked=false,pointAwarded=false,bonusResolved=false,photoToken=0,voiceCache=[];
const bonusPrompts=[v=>`Make a sentence using the Simple Past form “${first(v.v2)}.”`,v=>`Make a sentence using “have” or “has” with “${first(v.v3)}.”`,v=>`Ask another student a question using “${v.v1}.”`,v=>`Explain the difference: “${v.pastExample}” and “${v.perfectExample}”`];
function first(s){return s.split(' / ')[0]}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderTeamInputs(){const n=+$('teamCount').value;$('teamInputs').innerHTML=Array.from({length:n},(_,i)=>`<label>Team ${i+1}<input id="team${i}" type="text" value="Team ${i+1}" maxlength="18" required></label>`).join('')}
function makeState(deckIds){const n=+$('teamCount').value;return{version:3,status:'playing',teams:Array.from({length:n},(_,i)=>({name:$(`team${i}`).value.trim()||`Team ${i+1}`,score:0,streak:0,longest:0})),deck:deckIds,index:0,currentTeam:0,attempts:0,bonusEnabled:$('bonusEnabled').checked,streakEnabled:$('streakEnabled').checked,difficulty:$('difficulty').value,timerLength:+$('timerLength').value,muted:false,stats:{correct:0,missed:[],second:[],answered:0},review:false}}
function startGame(e){e?.preventDefault();const count=+$('questionCount').value,ids=C.shuffled(C.verbs).slice(0,count).map(v=>v.id);state=makeState(ids);save();showGame();renderRound()}
function showGame(){$('setup').classList.add('hidden');$('results').classList.add('hidden');$('game').classList.remove('hidden');$('newGameBtn').classList.remove('hidden')}
function currentVerb(){return C.verbs.find(v=>v.id===state.deck[state.index])}
function currentLevel(){if(state.difficulty!=='progressive')return +state.difficulty;const p=state.index/state.deck.length;return p<.25?1:p<.5?2:p<.75?3:4}
function renderRound(){clearInterval(timerId);answerLocked=false;pointAwarded=false;bonusResolved=false;selectedTile=null;state.attempts=0;const v=currentVerb(),level=currentLevel();renderProgress();renderTeams();renderClue(v,level);renderAnswer(v);$('feedbackPanel').classList.add('hidden');$('feedbackPanel').classList.remove('attempt-feedback');$('checkBtn').classList.remove('hidden');$('checkBtn').disabled=false;$('checkBtn').textContent='Check Answer';$('resetBtn').classList.remove('hidden');$('nextBtn').classList.add('hidden');$('bonusPanel').classList.add('hidden');$('streak').textContent=`🔥 ${state.teams[state.currentTeam].streak%3} / 3`;startTimer();announce(`${state.teams[state.currentTeam].name}, your turn. Card ${state.index+1} of ${state.deck.length}.`);save()}
function renderProgress(){const m=C.progressMeta(state.index,state.deck.length);$('progressText').textContent=m.text;$('progressBar').style.width=`${m.pct}%`;const bar=document.querySelector('.progress');bar.setAttribute('aria-valuenow',m.pct);bar.setAttribute('aria-valuetext',m.text)}
function renderTeams(){const active=state.teams[state.currentTeam];$('turnBanner').textContent=`▶ ${active.name.toUpperCase()} — YOUR TURN`;$('scoreboard').innerHTML=state.teams.map((t,i)=>`<div class="team-card ${i===state.currentTeam?'active':''}"><strong>${i===state.currentTeam?'▶ ':''}${esc(t.name)}</strong><small>${i===state.currentTeam?'Your turn':'Waiting'}</small><span class="team-score">${t.score}</span></div>`).join('')}
function renderClue(v,level){const labels=['','Level 1 · Supported','Level 2 · Visual','Level 3 · Sentence Clue','Level 4 · Listening Challenge'];$('levelChip').textContent=labels[level];const frame=$('photoFrame');frame.classList.toggle('hidden',level===4);$('spanishMeaning').classList.toggle('hidden',level>1);$('spanishMeaning').textContent=v.es;$('sentenceClue').classList.toggle('hidden',level!==3);$('sentenceClue').textContent=level===3?makeSentenceClue(v):'';$('hintBtn').classList.toggle('hidden',level===1);$('listenClueBtn').classList.remove('hidden');$('listenClueBtn').textContent=level===4?'🔊 Play Audio Clue':'🔊 Optional Audio Clue';if(level===4)setTimeout(()=>speak(v.v1),350);setPhoto(v)}
function makeSentenceClue(v){const form=first(v.v2);return v.pastExample.replace(new RegExp(`\\b${form.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i'),'_____')}
function setPhoto(v){const token=++photoToken,p=$('verbPhoto'),fallback=$('photoFallback'),col=v.cell%5,row=Math.floor(v.cell/5);p.style.backgroundImage=`url('${v.image}')`;p.style.backgroundPosition=`${col*25}% ${row*50}%`;p.setAttribute('aria-label',v.imageAlt);fallback.textContent=v.fallback;fallback.classList.add('hidden');const img=new Image();img.onload=()=>{if(token===photoToken)fallback.classList.add('hidden')};img.onerror=()=>{if(token===photoToken)fallback.classList.remove('hidden')};img.src=v.image}
function renderAnswer(v){const labels=[['V1 · Base Form','Forma base'],['V2 · Simple Past','Pasado simple'],['V3 · Past Participle','Participio pasado']];$('dropZones').innerHTML=labels.map((x,i)=>`<div class="drop-card"><label>${x[0]}<small>${x[1]}</small></label><div class="drop-zone" data-pos="${i}" data-placeholder="Drop V${i+1} here" tabindex="0" role="button" aria-label="Drop V${i+1} here"></div></div>`).join('');const forms=[v.v1,v.v2,v.v3];$('tileBank').innerHTML=C.shuffled(forms.map((value,i)=>({value,id:`${v.id}-form-${i}`}))).map(t=>`<button type="button" id="${t.id}" class="verb-tile" draggable="true" data-value="${esc(t.value)}" aria-pressed="false">${esc(t.value)}</button>`).join('');wireDnD()}
function wireDnD(){document.querySelectorAll('.verb-tile').forEach(tile=>{tile.addEventListener('dragstart',e=>{if(answerLocked)return e.preventDefault();e.dataTransfer.setData('text/plain',tile.id);selectTile(tile)});tile.addEventListener('click',()=>selectTile(tile))});document.querySelectorAll('.drop-zone').forEach(zone=>{zone.addEventListener('dragover',e=>{if(!answerLocked){e.preventDefault();zone.classList.add('over')}});zone.addEventListener('dragleave',()=>zone.classList.remove('over'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('over');placeTile(document.getElementById(e.dataTransfer.getData('text/plain')),zone)});zone.addEventListener('click',()=>{if(selectedTile)placeTile(selectedTile,zone)});zone.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&selectedTile){e.preventDefault();placeTile(selectedTile,zone)}})});const bank=$('tileBank');bank.addEventListener('dragover',e=>{if(!answerLocked)e.preventDefault()});bank.addEventListener('drop',e=>{e.preventDefault();returnToBank(document.getElementById(e.dataTransfer.getData('text/plain')))});bank.addEventListener('click',e=>{if(e.target===bank&&selectedTile)returnToBank(selectedTile)})}
function selectTile(tile){if(!tile||answerLocked)return;document.querySelectorAll('.verb-tile').forEach(t=>{t.classList.remove('selected');t.setAttribute('aria-pressed','false')});selectedTile=tile;tile.classList.add('selected');tile.setAttribute('aria-pressed','true');announce(`${tile.dataset.value} selected. Choose an answer box.`)}
function placeTile(tile,zone){if(!tile||!zone||answerLocked)return;const old=zone.querySelector('.verb-tile');if(old)$('tileBank').appendChild(old);zone.appendChild(tile);clearSelection();clearMarks();resumeAfterFeedback()}
function returnToBank(tile){if(!tile||answerLocked)return;$('tileBank').appendChild(tile);clearSelection();clearMarks();resumeAfterFeedback()}
function resumeAfterFeedback(){if(state.attempts===1&&!answerLocked&&$('feedbackPanel').classList.contains('attempt-feedback')){$('feedbackPanel').classList.add('hidden');$('feedbackPanel').classList.remove('attempt-feedback');runTimer()}}
function clearSelection(){if(selectedTile){selectedTile.classList.remove('selected');selectedTile.setAttribute('aria-pressed','false')}selectedTile=null}
function clearMarks(){document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('correct','wrong'))}
function resetAnswer(){if(answerLocked)return;resumeAfterFeedback();document.querySelectorAll('.drop-zone .verb-tile').forEach(t=>$('tileBank').appendChild(t));clearSelection();clearMarks();$('feedbackPanel').classList.add('hidden')}
function checkAnswer(){if(answerLocked||pointAwarded)return;const v=currentVerb(),zones=[...document.querySelectorAll('.drop-zone')];if(zones.some(z=>!z.querySelector('.verb-tile'))){showAttemptMessage('✕ Complete all three boxes before checking.');return}state.attempts++;let all=true;zones.forEach(z=>{const ok=C.accepts(z.querySelector('.verb-tile').dataset.value,v[['v1','v2','v3'][+z.dataset.pos]]);z.classList.add(ok?'correct':'wrong');if(!ok)all=false});if(all)completeCorrect(v);else if(state.attempts===1)firstWrong(v);else completeIncorrect(v);save()}
function showAttemptMessage(text){$('feedbackPanel').classList.remove('hidden');$('feedbackTitle').textContent='';$('formNote').textContent='';$('pronunciation').innerHTML='';document.querySelector('.examples').classList.add('hidden');$('feedbackStatus').className='feedback-status bad';$('feedbackStatus').textContent=text;pauseTimer()}
function firstWrong(v){showAttemptMessage('✕ Some forms are in the wrong places. Try again.');$('feedbackPanel').classList.add('attempt-feedback');if(!state.stats.second.includes(v.id))state.stats.second.push(v.id);$('checkBtn').textContent='Check Second Attempt';answerLocked=false;announce('Some forms are in the wrong places. You have one more attempt.')}
function completeCorrect(v){pointAwarded=true;answerLocked=true;pauseTimer();const team=state.teams[state.currentTeam];team.score++;team.streak++;team.longest=Math.max(team.longest,team.streak);state.stats.correct++;state.stats.answered++;if(team.streak%3===0&&state.streakEnabled){team.score++;showCelebration()}revealFeedback(v,true);renderTeams();announce(`Correct. ${team.name} earned one point.`)}
function completeIncorrect(v){answerLocked=true;pauseTimer();const team=state.teams[state.currentTeam];team.streak=0;state.stats.answered++;if(!state.stats.missed.includes(v.id))state.stats.missed.push(v.id);arrangeCorrect(v);revealFeedback(v,false);renderTeams();announce(`Second attempt incorrect. The correct forms are ${v.v1}, ${v.v2}, ${v.v3}.`)}
function arrangeCorrect(v){const values=[v.v1,v.v2,v.v3];document.querySelectorAll('.drop-zone').forEach((z,i)=>{const tile=[...document.querySelectorAll('.verb-tile')].find(t=>C.accepts(t.dataset.value,values[i])&&!t.dataset.used);if(tile){tile.dataset.used='1';z.replaceChildren(tile)}z.classList.remove('wrong');z.classList.add('correct')});document.querySelectorAll('.verb-tile').forEach(t=>delete t.dataset.used)}
function revealFeedback(v,correct){$('feedbackPanel').classList.remove('hidden');document.querySelector('.examples').classList.remove('hidden');$('feedbackStatus').className=`feedback-status ${correct?'good':'bad'}`;$('feedbackStatus').textContent=correct?'✓ Excellent!':'✕ Two attempts completed. Review the correct forms below.';$('feedbackTitle').textContent=`${v.v1} – ${v.v2} – ${v.v3}`;$('formNote').textContent=C.formNote(v);$('pastExample').textContent=v.pastExample;$('perfectExample').textContent=v.perfectExample;$('pronunciation').innerHTML=[['V1',v.v1],['V2',v.v2],['V3',v.v3]].map(x=>`<button class="btn secondary speak-btn" type="button" data-speak="${esc(first(x[1]))}" aria-label="Play pronunciation of ${x[0]} ${esc(first(x[1]))}">🔊 ${x[0]} · ${esc(x[1])}</button>`).join('');document.querySelectorAll('.speak-btn').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.speak)));$('checkBtn').classList.add('hidden');$('resetBtn').classList.add('hidden');if(state.bonusEnabled)showBonus(v);else showNext();$('streak').textContent=`🔥 ${state.teams[state.currentTeam].streak%3} / 3`}
function showBonus(v){$('bonusPanel').classList.remove('hidden');$('bonusPrompt').textContent=bonusPrompts[state.index%bonusPrompts.length](v);$('nextBtn').classList.add('hidden');bonusResolved=false}
function resolveBonus(award){if(bonusResolved)return;bonusResolved=true;if(award){state.teams[state.currentTeam].score++;renderTeams();announce('Bonus point awarded.')}$('bonusPanel').classList.add('hidden');showNext();save()}
function showNext(){$('nextBtn').classList.remove('hidden');$('nextBtn').focus()}
function nextRound(){state.index++;if(state.index>=state.deck.length)return finishGame();state.currentTeam=(state.currentTeam+1)%state.teams.length;renderRound()}
function startTimer(){clearInterval(timerId);timeLeft=state.timerLength;renderTimer();runTimer()}
function runTimer(){clearInterval(timerId);if(!timeLeft)return;timerId=setInterval(()=>{if(answerLocked)return;timeLeft--;renderTimer();if(timeLeft<=5&&!state.muted)beep();if(timeLeft<=0){clearInterval(timerId);completeIncorrect(currentVerb());save()}},1000)}
function renderTimer(){const total=state.timerLength||1,angle=Math.round((1-timeLeft/total)*360);$('timerNumber').textContent=state.timerLength?timeLeft:'∞';$('timer').style.setProperty('--timer-angle',`${angle}deg`);$('timer').classList.toggle('warning',timeLeft<=10&&timeLeft>5);$('timer').classList.toggle('danger',timeLeft<=5&&timeLeft>0);if(timeLeft===10||timeLeft===5)announce(`${timeLeft} seconds remaining.`)}
function pauseTimer(){clearInterval(timerId)}
function toggleMute(){state.muted=!state.muted;$('muteBtn').textContent=state.muted?'🔇':'🔊';$('muteBtn').setAttribute('aria-pressed',String(state.muted));$('muteBtn').setAttribute('aria-label',state.muted?'Unmute timer warning':'Mute timer warning');save()}
function beep(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=650;g.gain.value=.025;o.start();o.stop(c.currentTime+.055)}catch(_){}}
function loadVoices(){if(!('speechSynthesis'in window))return[];const voices=speechSynthesis.getVoices();if(voices.length)voiceCache=voices;return voiceCache}
function naturalEnglishVoice(){const voices=loadVoices().filter(v=>/^en[-_]/i.test(v.lang));const preferred=['natural','aria','jenny','guy','google us english','samantha','ava','zira','daniel'];return voices.sort((a,b)=>{const an=a.name.toLowerCase(),bn=b.name.toLowerCase();const ai=preferred.findIndex(x=>an.includes(x)),bi=preferred.findIndex(x=>bn.includes(x));const as=ai<0?99:ai,bs=bi<0?99:bi;if(as!==bs)return as-bs;if(a.localService!==b.localService)return a.localService?-1:1;return a.name.localeCompare(b.name)})[0]||null}
function speak(text,retry=true){if(!('speechSynthesis'in window)){announce('Pronunciation is not supported in this browser.');return}const clean=first(String(text)).trim();if(!clean)return;const voice=naturalEnglishVoice();if(!voice&&retry){setTimeout(()=>speak(clean,false),180);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${clean}.`);u.lang=voice?.lang||'en-US';u.voice=voice;u.rate=.94;u.pitch=1;u.volume=1;speechSynthesis.speak(u)}
function showCelebration(){$('celebration').classList.remove('hidden');setTimeout(()=>$('celebration').classList.add('hidden'),1800)}
function finishGame(){clearInterval(timerId);state.status='finished';save();$('game').classList.add('hidden');$('results').classList.remove('hidden');const best=Math.max(...state.teams.map(t=>t.score)),winners=state.teams.filter(t=>t.score===best).map(t=>t.name);$('resultsTitle').textContent=winners.length>1?`${winners.join(' & ')} tie!`:`${winners[0]} wins!`;$('finalScores').innerHTML=[...state.teams].sort((a,b)=>b.score-a.score).map(t=>`<div class="score-result">${esc(t.name)} · ${t.score} points</div>`).join('');const accuracy=state.stats.answered?Math.round(state.stats.correct/state.stats.answered*100):0,longest=Math.max(...state.teams.map(t=>t.longest));$('stats').innerHTML=`<div class="stat"><strong>${state.stats.correct}</strong>Total correct</div><div class="stat"><strong>${accuracy}%</strong>Accuracy</div><div class="stat"><strong>${longest}</strong>Longest streak</div><div class="stat"><strong>${state.stats.missed.length}</strong>Missed verbs</div>`;const hard=[...new Set([...state.stats.missed,...state.stats.second])].map(id=>C.verbs.find(v=>v.id===id)).filter(Boolean);$('difficultVerbs').innerHTML=hard.length?`<strong>Verbs to review:</strong> ${hard.map(v=>`${v.v1}–${v.v2}–${v.v3}`).join(' · ')}`:'<strong>Excellent work:</strong> No difficult verbs were recorded.';$('reviewBtn').classList.toggle('hidden',hard.length===0);sessionStorage.removeItem(SAVE_KEY)}
function reviewMissed(){const ids=[...new Set([...state.stats.missed,...state.stats.second])];state={...state,status:'playing',deck:C.shuffled(ids),index:0,currentTeam:0,attempts:0,review:true,teams:state.teams.map(t=>({...t,score:0,streak:0,longest:0})),stats:{correct:0,missed:[],second:[],answered:0}};save();showGame();renderRound()}
function playAgain(){const ids=C.shuffled(state.deck);state={...state,status:'playing',deck:ids,index:0,currentTeam:0,attempts:0,review:false,teams:state.teams.map(t=>({...t,score:0,streak:0,longest:0})),stats:{correct:0,missed:[],second:[],answered:0}};save();showGame();renderRound()}
function requestNew(){if(!state||state.status==='setup')return resetToSetup();$('confirmDialog').classList.remove('hidden');setTimeout(()=>$('continueBtn').focus(),0)}
function resetToSetup(){clearInterval(timerId);sessionStorage.removeItem(SAVE_KEY);state=null;$('confirmDialog').classList.add('hidden');$('resumeDialog').classList.add('hidden');$('game').classList.add('hidden');$('results').classList.add('hidden');$('setup').classList.remove('hidden');$('newGameBtn').classList.add('hidden');$('setupTitle').focus?.()}
function save(){if(state&&state.status==='playing')sessionStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function restore(){try{const raw=sessionStorage.getItem(SAVE_KEY);if(!raw)return;const saved=JSON.parse(raw);if(saved.version===3&&saved.status==='playing'&&saved.deck?.length){state=saved;$('resumeDialog').classList.remove('hidden');setTimeout(()=>$('resumeBtn').focus(),0)}}catch(_){sessionStorage.removeItem(SAVE_KEY)}}
function resume(){ $('resumeDialog').classList.add('hidden');showGame();renderRound() }
function announce(text){$('announcer').textContent='';requestAnimationFrame(()=>$('announcer').textContent=text)}
function showHint(){$('spanishMeaning').classList.remove('hidden');$('hintBtn').classList.add('hidden');announce(`Spanish hint: ${currentVerb().es}`)}
function bind(){renderTeamInputs();$('teamCount').addEventListener('change',renderTeamInputs);$('setupForm').addEventListener('submit',startGame);$('checkBtn').addEventListener('click',checkAnswer);$('resetBtn').addEventListener('click',resetAnswer);$('nextBtn').addEventListener('click',nextRound);$('muteBtn').addEventListener('click',toggleMute);$('hintBtn').addEventListener('click',showHint);$('listenClueBtn').addEventListener('click',()=>speak(currentVerb().v1));$('awardBonusBtn').addEventListener('click',()=>resolveBonus(true));$('noBonusBtn').addEventListener('click',()=>resolveBonus(false));$('skipBonusBtn').addEventListener('click',()=>resolveBonus(false));$('newGameBtn').addEventListener('click',requestNew);$('resultsNewBtn').addEventListener('click',requestNew);$('continueBtn').addEventListener('click',()=>{$('confirmDialog').classList.add('hidden')});$('confirmNewBtn').addEventListener('click',resetToSetup);$('reviewBtn').addEventListener('click',reviewMissed);$('playAgainBtn').addEventListener('click',playAgain);$('resumeBtn').addEventListener('click',resume);$('discardBtn').addEventListener('click',resetToSetup);document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('confirmDialog').classList.add('hidden');$('resumeDialog').classList.add('hidden')}})}
if('speechSynthesis'in window){loadVoices();speechSynthesis.addEventListener?.('voiceschanged',loadVoices)}
const errors=C.validateData();if(errors.length){console.error('Verb data validation failed',errors);document.body.innerHTML='<main class="app"><section class="card results"><h1>Game data needs attention</h1><p>Please contact the teacher.</p></section></main>'}else{bind();$('newGameBtn').classList.add('hidden');restore()}
})();
