(function(){
  const words=window.ADJECTIVES,$=s=>document.querySelector(s);let index=Number(localStorage.getItem('adj-index')||0);if(index<0||index>=words.length)index=0;
  let learned=new Set(JSON.parse(localStorage.getItem('adj-learned')||'[]')),quiz=[],quizAt=0,score=0;
  const els={image:$('#adjectiveImage'),loading:$('#loading'),category:$('#categoryBadge'),counter:$('#counter'),word:$('#word'),ipa:$('#ipa'),spanish:$('#spanish'),example:$('#example'),exampleSpanish:$('#exampleSpanish'),bar:$('#progressBar'),known:$('#knownBtn')};
  function save(){localStorage.setItem('adj-index',index);localStorage.setItem('adj-learned',JSON.stringify([...learned]))}
  function imageUrl(w,i){const prompt=encodeURIComponent(`Modern educational visual illustrating the English adjective "${w.word}": ${w.image||'adult daily life'}. Realistic, culturally inclusive, professional adult ESL material, clear single concept, clean composition, no words or letters.`);return `https://image.pollinations.ai/prompt/${prompt}?width=1200&height=900&seed=${i+401}&nologo=true&safe=true`}
  function fallback(w){const hue=(index*47)%360,svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${hue} 72% 82%)"/><stop offset="1" stop-color="hsl(${(hue+70)%360} 75% 94%)"/></linearGradient></defs><rect width="1200" height="900" rx="40" fill="url(%23g)"/><circle cx="600" cy="380" r="190" fill="white" opacity=".72"/><text x="600" y="435" text-anchor="middle" font-family="Arial" font-size="220">${w.icon||'✨'}</text><text x="600" y="720" text-anchor="middle" font-family="Arial" font-size="92" font-weight="700" fill="%2317193f">${w.word}</text></svg>`;return `data:image/svg+xml,${encodeURIComponent(svg)}`}
  function render(){const w=words[index];els.counter.textContent=`ADJECTIVE ${index+1} OF ${words.length}`;els.word.textContent=w.word;els.ipa.textContent=w.ipa;els.spanish.textContent=w.es;els.category.textContent=w.category;els.example.textContent=w.example;els.exampleSpanish.textContent=w.exampleEs;els.bar.style.width=`${(index+1)/words.length*100}%`;els.known.classList.toggle('active',learned.has(index));els.known.textContent=learned.has(index)?'✓ Learned':'✓ Mark learned';$('#prevBtn').disabled=index===0;$('#nextBtn').textContent=index===words.length-1?'Finish':'Next →';els.loading.hidden=false;els.image.classList.remove('ready');els.image.alt=`Visual example of the adjective ${w.word}`;els.image.onerror=()=>{els.image.onerror=null;els.image.src=fallback(w)};els.image.onload=()=>{els.loading.hidden=true;els.image.classList.add('ready')};els.image.src=imageUrl(w,index);save();preload(index+1)}
  function preload(i){if(i>=words.length)return;const img=new Image();img.src=imageUrl(words[i],i)}
  function speak(text,rate=.86){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;const v=speechSynthesis.getVoices();u.voice=v.find(x=>x.lang==='en-US'&&/Natural|Samantha|Google US English/i.test(x.name))||v.find(x=>x.lang==='en-US')||null;speechSynthesis.speak(u)}
  function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function move(amount){const next=Math.max(0,Math.min(words.length-1,index+amount));if(next===index&&amount>0){toast('You completed all 200 adjectives!');return}index=next;render();$('#lesson').focus()}
  function openLibrary(){buildLibrary();$('#libraryDialog').showModal();$('#searchInput').focus()}
  function buildLibrary(){const cats=['All',...new Set(words.map(w=>w.category))],select=$('#categorySelect');if(!select.options.length)select.innerHTML=cats.map(c=>`<option>${c}</option>`).join('');const q=$('#searchInput').value.toLowerCase().trim(),cat=select.value||'All';const filtered=words.map((w,i)=>({...w,i})).filter(w=>(cat==='All'||w.category===cat)&&(!q||`${w.word} ${w.es}`.toLowerCase().includes(q)));$('#learnedCount').textContent=`${learned.size} learned`;$('#wordGrid').innerHTML=filtered.map(w=>`<button class="word-chip ${learned.has(w.i)?'learned':''}" data-index="${w.i}" type="button"><strong>${w.i+1}. ${w.word}</strong><span>${w.es} · ${w.ipa}</span></button>`).join('')||'<p>No matching adjectives.</p>';document.querySelectorAll('.word-chip').forEach(b=>b.onclick=()=>{index=Number(b.dataset.index);$('#libraryDialog').close();render()})}
  function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
  function startQuiz(){quiz=shuffle(words.map((w,i)=>({...w,i}))).slice(0,5);quizAt=0;score=0;$('#quizDialog').showModal();renderQuestion()}
  function renderQuestion(){const box=$('#quizContent');if(quizAt>=quiz.length){box.innerHTML=`<div class="quiz-result"><p>Quiz complete</p><strong>${score}/5</strong><p>${score===5?'Excellent work!':score>=3?'Good work—keep practicing!':'Review the words and try again.'}</p><button id="retryQuiz" class="button primary quiz-next" type="button">Try Another Quiz</button></div>`;$('#retryQuiz').onclick=startQuiz;return}const answer=quiz[quizAt],others=shuffle(words.filter(w=>w.es!==answer.es)).slice(0,3),options=shuffle([answer,...others]);box.innerHTML=`<p class="quiz-progress">Question ${quizAt+1} of 5</p><p class="quiz-question">What is the Spanish meaning of <q>${answer.word}</q>?</p><div class="quiz-options">${options.map(o=>`<button class="quiz-option" data-answer="${o.es===answer.es}" type="button">${o.es}</button>`).join('')}</div><p id="quizFeedback" class="quiz-feedback" aria-live="polite"></p><button id="quizNext" class="button primary quiz-next" type="button" hidden>Next →</button>`;document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='true';if(ok)score++;document.querySelectorAll('.quiz-option').forEach(x=>{x.disabled=true;if(x.dataset.answer==='true')x.classList.add('correct')});if(!ok)b.classList.add('wrong');$('#quizFeedback').textContent=ok?`Correct! ${answer.word} means ${answer.es}.`:`The correct answer is ${answer.es}.`;$('#quizNext').hidden=false});$('#quizNext').onclick=()=>{quizAt++;renderQuestion()}}
  $('#prevBtn').onclick=()=>move(-1);$('#nextBtn').onclick=()=>move(1);$('#speakBtn').onclick=()=>speak(words[index].word,.8);$('#sentenceBtn').onclick=()=>speak(words[index].example,.88);els.known.onclick=()=>{learned.has(index)?learned.delete(index):learned.add(index);save();render();toast(learned.has(index)?'Marked as learned!':'Removed from learned words')};$('#libraryBtn').onclick=openLibrary;$('#quizBtn').onclick=startQuiz;$('#searchInput').oninput=buildLibrary;$('#categorySelect').onchange=buildLibrary;document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);if(e.key===' ')speak(words[index].word,.8)});render();
})();
