(function(){
const rows=[
// Feelings (1–20)
['happy','/ˈhæpi/','feliz','She feels happy today.','Ella se siente feliz hoy.','Feelings','happy smiling adult','😊'],
['sad','/sæd/','triste','He looked sad after the news.','Él se veía triste después de la noticia.','Feelings','sad adult portrait','😢'],
['angry','/ˈæŋɡri/','enojado/a','The customer is angry about the delay.','El cliente está enojado por el retraso.','Feelings','angry customer adult','😠'],
['excited','/ɪkˈsaɪtɪd/','emocionado/a','We are excited about the trip.','Estamos emocionados por el viaje.','Feelings','excited adults celebration','🤩'],
['tired','/ˈtaɪərd/','cansado/a','I am tired after work.','Estoy cansado después del trabajo.','Feelings','tired adult after work','😴'],
['nervous','/ˈnɜrvəs/','nervioso/a','She is nervous about the interview.','Ella está nerviosa por la entrevista.','Feelings','nervous job interview adult','😟'],
['worried','/ˈwɜrid/','preocupado/a','They are worried about the weather.','Están preocupados por el clima.','Feelings','worried adult looking outside','😰'],
['calm','/kɑm/','tranquilo/a','The nurse remained calm.','La enfermera permaneció tranquila.','Feelings','calm nurse professional','😌'],
['surprised','/sərˈpraɪzd/','sorprendido/a','He was surprised by the gift.','Él quedó sorprendido por el regalo.','Feelings','surprised adult gift','😮'],
['bored','/bɔrd/','aburrido/a','The long meeting made us bored.','La reunión larga nos dejó aburridos.','Feelings','bored adults meeting','🥱'],
['afraid','/əˈfreɪd/','asustado/a','The child is afraid of the storm.','El niño está asustado por la tormenta.','Feelings','afraid family thunderstorm','😨'],
['proud','/praʊd/','orgulloso/a','Her family is proud of her.','Su familia está orgullosa de ella.','Feelings','proud family graduation adult','🏆'],
['embarrassed','/ɪmˈbærəst/','avergonzado/a','I felt embarrassed by my mistake.','Me sentí avergonzado por mi error.','Feelings','embarrassed adult mistake','😳'],
['lonely','/ˈloʊnli/','solo/a','He felt lonely in the new city.','Él se sintió solo en la ciudad nueva.','Feelings','lonely adult city','😔'],
['comfortable','/ˈkʌmftərbəl/','cómodo/a','This chair is very comfortable.','Esta silla es muy cómoda.','Feelings','comfortable chair adult home','🛋️'],
['uncomfortable','/ʌnˈkʌmftərbəl/','incómodo/a','These shoes are uncomfortable.','Estos zapatos son incómodos.','Feelings','uncomfortable shoes adult','👞'],
['satisfied','/ˈsætɪsfaɪd/','satisfecho/a','The client is satisfied with the service.','El cliente está satisfecho con el servicio.','Feelings','satisfied customer service','👍'],
['disappointed','/ˌdɪsəˈpɔɪntɪd/','decepcionado/a','We were disappointed with the result.','Estuvimos decepcionados con el resultado.','Feelings','disappointed adult results','🙁'],
['grateful','/ˈɡreɪtfəl/','agradecido/a','I am grateful for your help.','Estoy agradecido por tu ayuda.','Feelings','grateful adults helping','🙏'],
['hopeful','/ˈhoʊpfəl/','esperanzado/a','She is hopeful about the future.','Ella está esperanzada sobre el futuro.','Feelings','hopeful adult sunrise future','🌅'],

// Personality (21–40)
['kind','/kaɪnd/','amable','Our new neighbor is kind.','Nuestro nuevo vecino es amable.','Personality','kind neighbor helping','🤝'],
['friendly','/ˈfrɛndli/','amistoso/a','The receptionist is friendly.','La recepcionista es amistosa.','Personality','friendly receptionist','🙂'],
['honest','/ˈɑnɪst/','honesto/a','An honest employee tells the truth.','Un empleado honesto dice la verdad.','Personality','honest employee workplace','🤚'],
['patient','/ˈpeɪʃənt/','paciente','Our teacher is patient with beginners.','Nuestro maestro es paciente con los principiantes.','Personality','patient adult teacher students','🧘'],
['polite','/pəˈlaɪt/','educado/a','The waiter was polite to every guest.','El mesero fue educado con cada cliente.','Personality','polite waiter restaurant','🙋'],
['helpful','/ˈhɛlpfəl/','servicial','The store employee was helpful.','El empleado de la tienda fue servicial.','Personality','helpful store employee','🫱'],
['generous','/ˈdʒɛnərəs/','generoso/a','Our generous friend shared her lunch.','Nuestra amiga generosa compartió su almuerzo.','Personality','generous adult sharing food','🎁'],
['brave','/breɪv/','valiente','The brave firefighter entered the building.','El bombero valiente entró al edificio.','Personality','brave firefighter adult','🧑‍🚒'],
['careful','/ˈkɛrfəl/','cuidadoso/a','Be careful with the hot pan.','Ten cuidado con la sartén caliente.','Personality','careful adult cooking','⚠️'],
['confident','/ˈkɑnfɪdənt/','seguro/a','She sounded confident during the presentation.','Ella sonó segura durante la presentación.','Personality','confident woman presentation','💪'],
['funny','/ˈfʌni/','gracioso/a','My coworker tells funny stories.','Mi compañero de trabajo cuenta historias graciosas.','Personality','funny coworkers laughing','😂'],
['serious','/ˈsɪriəs/','serio/a','This is a serious problem.','Este es un problema serio.','Personality','serious adult meeting','🧐'],
['quiet','/ˈkwaɪət/','callado/a','The new student is quiet.','El estudiante nuevo es callado.','Personality','quiet adult student classroom','🤫'],
['shy','/ʃaɪ/','tímido/a','He is shy around new people.','Él es tímido con personas nuevas.','Personality','shy adult social group','🫣'],
['active','/ˈæktɪv/','activo/a','My grandfather is still very active.','Mi abuelo todavía es muy activo.','Personality','active older adult exercise','🏃'],
['lazy','/ˈleɪzi/','perezoso/a','I feel lazy on rainy Sundays.','Me siento perezoso los domingos lluviosos.','Personality','lazy adult sofa sunday','🛋️'],
['creative','/kriˈeɪtɪv/','creativo/a','She found a creative solution.','Ella encontró una solución creativa.','Personality','creative adult designer','🎨'],
['curious','/ˈkjʊriəs/','curioso/a','The curious student asked many questions.','El estudiante curioso hizo muchas preguntas.','Personality','curious adult student questions','❓'],
['responsible','/rɪˈspɑnsəbəl/','responsable','He is responsible for the schedule.','Él es responsable del horario.','Personality','responsible employee schedule','📋'],
['organized','/ˈɔrɡənaɪzd/','organizado/a','Her desk is always organized.','Su escritorio siempre está organizado.','Personality','organized modern office desk','🗂️'],

// Size and shape (41–60)
['big','/bɪɡ/','grande','They live in a big house.','Ellos viven en una casa grande.','Size & Shape','big modern house','🏠'],
['small','/smɔl/','pequeño/a','I ordered a small coffee.','Pedí un café pequeño.','Size & Shape','small coffee cup','☕'],
['large','/lɑrdʒ/','grande','We need a large table for the meeting.','Necesitamos una mesa grande para la reunión.','Size & Shape','large conference table','🪑'],
['tiny','/ˈtaɪni/','diminuto/a','There is a tiny scratch on the screen.','Hay un rayón diminuto en la pantalla.','Size & Shape','tiny scratch phone screen','🔎'],
['tall','/tɔl/','alto/a','That tall building is downtown.','Ese edificio alto está en el centro.','Size & Shape','tall downtown building','🏢'],
['short','/ʃɔrt/','corto/a; bajo/a','We took a short break.','Tomamos un descanso corto.','Size & Shape','short work break coffee','⏱️'],
['long','/lɔŋ/','largo/a','It was a long drive home.','Fue un viaje largo a casa.','Size & Shape','long road drive','🛣️'],
['wide','/waɪd/','ancho/a','The truck needs a wide parking space.','La camioneta necesita un espacio de estacionamiento ancho.','Size & Shape','wide parking space truck','↔️'],
['narrow','/ˈnæroʊ/','estrecho/a','This hallway is very narrow.','Este pasillo es muy estrecho.','Size & Shape','narrow hallway modern','🚪'],
['thick','/θɪk/','grueso/a','She wore a thick coat.','Ella usó un abrigo grueso.','Size & Shape','thick winter coat adult','🧥'],
['thin','/θɪn/','delgado/a','Cut the vegetables into thin slices.','Corta los vegetales en rodajas delgadas.','Size & Shape','thin vegetable slices cooking','🥒'],
['heavy','/ˈhɛvi/','pesado/a','This box is too heavy.','Esta caja es demasiado pesada.','Size & Shape','heavy moving box adult','📦'],
['light','/laɪt/','ligero/a','This laptop is light and easy to carry.','Esta computadora portátil es ligera y fácil de llevar.','Size & Shape','lightweight laptop travel','💻'],
['deep','/dip/','profundo/a','The water is deep near the bridge.','El agua es profunda cerca del puente.','Size & Shape','deep water bridge','🌊'],
['shallow','/ˈʃæloʊ/','poco profundo/a','The children played in shallow water.','Los niños jugaron en agua poco profunda.','Size & Shape','shallow water family','🏖️'],
['round','/raʊnd/','redondo/a','We bought a round table.','Compramos una mesa redonda.','Size & Shape','round dining table','⭕'],
['square','/skwɛr/','cuadrado/a','The room has a square window.','La habitación tiene una ventana cuadrada.','Size & Shape','square window room','⬜'],
['flat','/flæt/','plano/a','Put the box on a flat surface.','Pon la caja sobre una superficie plana.','Size & Shape','flat work surface box','➖'],
['straight','/streɪt/','recto/a','Drive straight for two miles.','Conduce en línea recta por dos millas.','Size & Shape','straight road driving','⬆️'],
['curved','/kɜrvd/','curvo/a','The road becomes curved after the hill.','La carretera se vuelve curva después de la colina.','Size & Shape','curved road hill','〰️'],

// Appearance (61–80)
['beautiful','/ˈbjutəfəl/','hermoso/a','The park is beautiful in the fall.','El parque es hermoso en el otoño.','Appearance','beautiful fall park adults','🌳'],
['handsome','/ˈhænsəm/','guapo','He looks handsome in that suit.','Él se ve guapo con ese traje.','Appearance','handsome adult man suit','👔'],
['pretty','/ˈprɪti/','bonito/a','She bought a pretty dress.','Ella compró un vestido bonito.','Appearance','pretty modern dress adult','👗'],
['attractive','/əˈtræktɪv/','atractivo/a','The apartment has an attractive kitchen.','El apartamento tiene una cocina atractiva.','Appearance','attractive modern kitchen','✨'],
['cute','/kjut/','lindo/a','That is a cute family photo.','Esa es una foto familiar linda.','Appearance','cute family photo adults','📷'],
['clean','/klin/','limpio/a','The hotel room is clean.','La habitación del hotel está limpia.','Appearance','clean modern hotel room','🧼'],
['dirty','/ˈdɜrti/','sucio/a','My work shoes are dirty.','Mis zapatos de trabajo están sucios.','Appearance','dirty work boots','🥾'],
['neat','/nit/','ordenado/a','His handwriting is neat.','Su letra es ordenada.','Appearance','neat handwriting notebook','✍️'],
['messy','/ˈmɛsi/','desordenado/a','The kitchen is messy after dinner.','La cocina está desordenada después de la cena.','Appearance','messy kitchen after dinner','🍽️'],
['young','/jʌŋ/','joven','The young doctor explained everything clearly.','El doctor joven explicó todo claramente.','Appearance','young adult doctor','🧑‍⚕️'],
['old','/oʊld/','viejo/a; antiguo/a','They repaired an old house.','Ellos repararon una casa antigua.','Appearance','old house renovation adults','🏚️'],
['modern','/ˈmɑdərn/','moderno/a','Our office has modern furniture.','Nuestra oficina tiene muebles modernos.','Appearance','modern office furniture','🏙️'],
['traditional','/trəˈdɪʃənəl/','tradicional','They served a traditional meal.','Sirvieron una comida tradicional.','Appearance','traditional family meal','🍲'],
['colorful','/ˈkʌlərfəl/','colorido/a','The market is bright and colorful.','El mercado es brillante y colorido.','Appearance','colorful outdoor market','🌈'],
['plain','/pleɪn/','sencillo/a','He wore a plain white shirt.','Él usó una camisa blanca sencilla.','Appearance','plain white shirt adult','👕'],
['bright','/braɪt/','brillante','The room is bright in the morning.','La habitación está brillante por la mañana.','Appearance','bright morning room','☀️'],
['dark','/dɑrk/','oscuro/a','The parking lot is dark at night.','El estacionamiento está oscuro de noche.','Appearance','dark parking lot night','🌙'],
['elegant','/ˈɛləɡənt/','elegante','She chose an elegant black dress.','Ella eligió un vestido negro elegante.','Appearance','elegant black dress adult','🖤'],
['casual','/ˈkæʒuəl/','informal','Friday is a casual workday.','El viernes es un día laboral informal.','Appearance','casual office clothes adults','👟'],
['sharp','/ʃɑrp/','afilado/a; elegante','He looks sharp in his new jacket.','Él se ve elegante con su chaqueta nueva.','Appearance','sharp dressed adult jacket','🧥'],

// Quality (81–100)
['good','/ɡʊd/','bueno/a','That is a good idea.','Esa es una buena idea.','Quality','good idea team meeting','✅'],
['bad','/bæd/','malo/a','The storm caused bad traffic.','La tormenta causó tráfico malo.','Quality','bad traffic storm','⛔'],
['excellent','/ˈɛksələnt/','excelente','She did an excellent job.','Ella hizo un trabajo excelente.','Quality','excellent employee success','🌟'],
['perfect','/ˈpɜrfɪkt/','perfecto/a','This time is perfect for me.','Esta hora es perfecta para mí.','Quality','perfect appointment time calendar','👌'],
['useful','/ˈjusfəl/','útil','This app is useful at work.','Esta aplicación es útil en el trabajo.','Quality','useful mobile app work','📱'],
['useless','/ˈjusləs/','inútil','The broken charger is useless.','El cargador roto es inútil.','Quality','broken useless charger','🔌'],
['important','/ɪmˈpɔrtənt/','importante','It is important to arrive on time.','Es importante llegar a tiempo.','Quality','important appointment clock','❗'],
['necessary','/ˈnɛsəˌsɛri/','necesario/a','A valid ID is necessary.','Una identificación válida es necesaria.','Quality','necessary identification card','🪪'],
['possible','/ˈpɑsəbəl/','posible','A same-day appointment is possible.','Una cita el mismo día es posible.','Quality','possible appointment calendar','🟢'],
['impossible','/ɪmˈpɑsəbəl/','imposible','It is impossible to finish in five minutes.','Es imposible terminar en cinco minutos.','Quality','impossible deadline clock work','🚫'],
['easy','/ˈizi/','fácil','The online form is easy to complete.','El formulario en línea es fácil de completar.','Quality','easy online form adult','👍'],
['difficult','/ˈdɪfəkəlt/','difícil','The first week was difficult.','La primera semana fue difícil.','Quality','difficult work week adult','🧩'],
['simple','/ˈsɪmpəl/','simple','The instructions are simple.','Las instrucciones son simples.','Quality','simple instructions document','📄'],
['complex','/kəmˈplɛks/','complejo/a','This is a complex medical issue.','Este es un asunto médico complejo.','Quality','complex medical discussion doctor','🧠'],
['correct','/kəˈrɛkt/','correcto/a','Your answer is correct.','Tu respuesta es correcta.','Quality','correct answer adult student','✔️'],
['wrong','/rɔŋ/','incorrecto/a','I entered the wrong address.','Ingresé la dirección incorrecta.','Quality','wrong address map phone','❌'],
['safe','/seɪf/','seguro/a','This neighborhood feels safe.','Este vecindario se siente seguro.','Quality','safe neighborhood families','🛡️'],
['dangerous','/ˈdeɪndʒərəs/','peligroso/a','Driving in ice can be dangerous.','Manejar sobre hielo puede ser peligroso.','Quality','dangerous icy road driving','⚠️'],
['strong','/strɔŋ/','fuerte','We need a strong password.','Necesitamos una contraseña fuerte.','Quality','strong password security','🔐'],
['weak','/wik/','débil','The phone has a weak signal.','El teléfono tiene una señal débil.','Quality','weak phone signal','📶'],

// Condition (101–120)
['new','/nu/','nuevo/a','She started a new job.','Ella comenzó un trabajo nuevo.','Condition','new job office adult','🆕'],
['used','/juzd/','usado/a','We bought a used car.','Compramos un carro usado.','Condition','used car dealership adults','🚗'],
['broken','/ˈbroʊkən/','roto/a','The washing machine is broken.','La lavadora está rota.','Condition','broken washing machine repair','🛠️'],
['open','/ˈoʊpən/','abierto/a','The pharmacy is open.','La farmacia está abierta.','Condition','open pharmacy storefront','🔓'],
['closed','/kloʊzd/','cerrado/a','The bank is closed today.','El banco está cerrado hoy.','Condition','closed bank sign','🔒'],
['full','/fʊl/','lleno/a','The parking lot is full.','El estacionamiento está lleno.','Condition','full parking lot cars','🅿️'],
['empty','/ˈɛmpti/','vacío/a','The gas tank is almost empty.','El tanque de gasolina está casi vacío.','Condition','empty gas tank dashboard','⛽'],
['busy','/ˈbɪzi/','ocupado/a','The clinic is busy this morning.','La clínica está ocupada esta mañana.','Condition','busy medical clinic adults','🏥'],
['free','/fri/','libre; gratis','Are you free after work?','¿Estás libre después del trabajo?','Condition','free time adult after work','🕕'],
['ready','/ˈrɛdi/','listo/a','Dinner is ready.','La cena está lista.','Condition','dinner ready family table','🍽️'],
['late','/leɪt/','tarde; atrasado/a','The bus is late again.','El autobús está atrasado otra vez.','Condition','late bus stop adults','🚌'],
['early','/ˈɜrli/','temprano/a','I arrived early for my appointment.','Llegué temprano a mi cita.','Condition','early appointment waiting room','⏰'],
['hot','/hɑt/','caliente','The soup is very hot.','La sopa está muy caliente.','Condition','hot soup steam restaurant','🔥'],
['cold','/koʊld/','frío/a','The water is too cold.','El agua está demasiado fría.','Condition','cold water glass ice','🧊'],
['warm','/wɔrm/','tibio/a; cálido/a','The bread is still warm.','El pan todavía está tibio.','Condition','warm fresh bread','🥖'],
['cool','/kul/','fresco/a','The evening air feels cool.','El aire de la noche se siente fresco.','Condition','cool evening outdoors adults','🌬️'],
['wet','/wɛt/','mojado/a','The floor is wet.','El piso está mojado.','Condition','wet floor caution','💧'],
['dry','/draɪ/','seco/a','My skin gets dry in winter.','Mi piel se reseca en invierno.','Condition','dry skin winter lotion adult','🏜️'],
['fresh','/frɛʃ/','fresco/a','We bought fresh vegetables.','Compramos vegetales frescos.','Condition','fresh vegetables supermarket','🥬'],
['stale','/steɪl/','rancio/a; duro/a','This bread tastes stale.','Este pan sabe rancio.','Condition','stale bread kitchen','🍞'],

// Sensory and texture (121–140)
['soft','/sɔft/','suave','This blanket is soft.','Esta cobija es suave.','Sensory & Texture','soft blanket home adult','🧸'],
['hard','/hɑrd/','duro/a','The ground is hard and dry.','El suelo está duro y seco.','Sensory & Texture','hard dry ground','🪨'],
['smooth','/smuð/','liso/a','The table has a smooth surface.','La mesa tiene una superficie lisa.','Sensory & Texture','smooth wooden table surface','🫧'],
['rough','/rʌf/','áspero/a','The wall feels rough.','La pared se siente áspera.','Sensory & Texture','rough wall texture hand','🧱'],
['sweet','/swit/','dulce','The tea is too sweet.','El té está demasiado dulce.','Sensory & Texture','sweet tea cafe','🍯'],
['sour','/ˈsaʊər/','ácido/a','The lemon tastes sour.','El limón sabe ácido.','Sensory & Texture','sour lemon adult tasting','🍋'],
['bitter','/ˈbɪtər/','amargo/a','The coffee is bitter.','El café está amargo.','Sensory & Texture','bitter black coffee adult','☕'],
['spicy','/ˈspaɪsi/','picante','This sauce is very spicy.','Esta salsa es muy picante.','Sensory & Texture','spicy sauce food adult','🌶️'],
['salty','/ˈsɔlti/','salado/a','The soup is a little salty.','La sopa está un poco salada.','Sensory & Texture','salty soup restaurant','🧂'],
['delicious','/dɪˈlɪʃəs/','delicioso/a','The homemade meal was delicious.','La comida casera estuvo deliciosa.','Sensory & Texture','delicious homemade meal family','😋'],
['loud','/laʊd/','ruidoso/a; fuerte','The music is too loud.','La música está demasiado fuerte.','Sensory & Texture','loud music speakers adults','🔊'],
['silent','/ˈsaɪlənt/','silencioso/a','The office was completely silent.','La oficina estaba completamente silenciosa.','Sensory & Texture','silent empty office','🔇'],
['noisy','/ˈnɔɪzi/','ruidoso/a','Our street is noisy at night.','Nuestra calle es ruidosa de noche.','Sensory & Texture','noisy city street night','🚦'],
['fragrant','/ˈfreɪɡrənt/','fragante','The garden is full of fragrant flowers.','El jardín está lleno de flores fragantes.','Sensory & Texture','fragrant flowers garden adult','🌸'],
['smelly','/ˈsmɛli/','maloliente','Please take out the smelly trash.','Por favor, saca la basura maloliente.','Sensory & Texture','smelly trash kitchen adult','🗑️'],
['shiny','/ˈʃaɪni/','brillante','He bought a shiny new car.','Él compró un carro nuevo y brillante.','Sensory & Texture','shiny new car adult','✨'],
['dull','/dʌl/','opaco/a; aburrido/a','The old paint looks dull.','La pintura vieja se ve opaca.','Sensory & Texture','dull old paint wall','◽'],
['transparent','/trænˈspɛrənt/','transparente','The container has a transparent lid.','El recipiente tiene una tapa transparente.','Sensory & Texture','transparent food container lid','🫙'],
['flexible','/ˈflɛksəbəl/','flexible','My work schedule is flexible.','Mi horario de trabajo es flexible.','Sensory & Texture','flexible work schedule adult','🤸'],
['stiff','/stɪf/','rígido/a','My neck feels stiff this morning.','Mi cuello se siente rígido esta mañana.','Sensory & Texture','stiff neck adult morning','🧍'],

// Time and availability (141–160)
['daily','/ˈdeɪli/','diario/a','Walking is part of my daily routine.','Caminar es parte de mi rutina diaria.','Time & Availability','daily walking routine adult','📅'],
['weekly','/ˈwikli/','semanal','We have a weekly staff meeting.','Tenemos una reunión semanal del personal.','Time & Availability','weekly staff meeting','🗓️'],
['monthly','/ˈmʌnθli/','mensual','The monthly payment is due tomorrow.','El pago mensual vence mañana.','Time & Availability','monthly payment calendar','💳'],
['annual','/ˈænjuəl/','anual','The company holds an annual picnic.','La compañía realiza un picnic anual.','Time & Availability','annual company picnic adults','🎉'],
['frequent','/ˈfrikwənt/','frecuente','Frequent practice improves pronunciation.','La práctica frecuente mejora la pronunciación.','Time & Availability','frequent English practice adult','🔁'],
['occasional','/əˈkeɪʒənəl/','ocasional','We have occasional internet problems.','Tenemos problemas ocasionales de internet.','Time & Availability','occasional internet problem laptop','📡'],
['regular','/ˈrɛɡjələr/','regular','Regular exercise is good for you.','El ejercicio regular es bueno para ti.','Time & Availability','regular exercise adults','🏋️'],
['unusual','/ʌnˈjuʒuəl/','inusual','That is an unusual sound.','Ese es un sonido inusual.','Time & Availability','unusual sound adult listening','👂'],
['current','/ˈkɜrənt/','actual','Please enter your current address.','Por favor, ingresa tu dirección actual.','Time & Availability','current address online form','📍'],
['previous','/ˈpriviəs/','anterior','My previous job was in retail.','Mi trabajo anterior era en ventas.','Time & Availability','previous retail job adult','⏮️'],
['next','/nɛkst/','próximo/a','Our next class is on Tuesday.','Nuestra próxima clase es el martes.','Time & Availability','next class calendar adults','⏭️'],
['recent','/ˈrisənt/','reciente','A recent update fixed the problem.','Una actualización reciente solucionó el problema.','Time & Availability','recent software update laptop','🆙'],
['future','/ˈfjutʃər/','futuro/a','We discussed our future plans.','Hablamos de nuestros planes futuros.','Time & Availability','future plans adults discussion','🔮'],
['permanent','/ˈpɜrmənənt/','permanente','She found a permanent position.','Ella encontró un puesto permanente.','Time & Availability','permanent job position adult','🏢'],
['temporary','/ˈtɛmpəˌrɛri/','temporal','This is a temporary solution.','Esta es una solución temporal.','Time & Availability','temporary solution repair','⏳'],
['available','/əˈveɪləbəl/','disponible','The doctor is available at three.','El doctor está disponible a las tres.','Time & Availability','available doctor appointment','🟢'],
['unavailable','/ˌʌnəˈveɪləbəl/','no disponible','The manager is unavailable right now.','El gerente no está disponible ahora.','Time & Availability','unavailable manager office','🔴'],
['immediate','/ɪˈmidiət/','inmediato/a','The patient needs immediate help.','El paciente necesita ayuda inmediata.','Time & Availability','immediate medical help adult','🚑'],
['final','/ˈfaɪnəl/','final','This is the final question.','Esta es la pregunta final.','Time & Availability','final question test adult','🏁'],
['first','/fɜrst/','primero/a','Today is my first day at work.','Hoy es mi primer día de trabajo.','Time & Availability','first day work adult','1️⃣'],

// Work and ability (161–180)
['professional','/prəˈfɛʃənəl/','profesional','Her email sounds professional.','Su correo electrónico suena profesional.','Work & Ability','professional email office adult','💼'],
['experienced','/ɪkˈspɪriənst/','experimentado/a','We hired an experienced mechanic.','Contratamos a un mecánico experimentado.','Work & Ability','experienced mechanic adult','🔧'],
['inexperienced','/ˌɪnɪkˈspɪriənst/','inexperto/a','The new worker is inexperienced but eager.','El trabajador nuevo es inexperto pero tiene entusiasmo.','Work & Ability','inexperienced new worker training','🌱'],
['skilled','/skɪld/','capacitado/a','She is a skilled dental assistant.','Ella es una asistente dental capacitada.','Work & Ability','skilled dental assistant adult','🦷'],
['talented','/ˈtæləntɪd/','talentoso/a','He is a talented cook.','Él es un cocinero talentoso.','Work & Ability','talented adult cook kitchen','👨‍🍳'],
['intelligent','/ɪnˈtɛlədʒənt/','inteligente','She is an intelligent student.','Ella es una estudiante inteligente.','Work & Ability','intelligent adult student','🧠'],
['smart','/smɑrt/','inteligente','That was a smart decision.','Esa fue una decisión inteligente.','Work & Ability','smart decision business adults','💡'],
['practical','/ˈpræktɪkəl/','práctico/a','This course teaches practical English.','Este curso enseña inglés práctico.','Work & Ability','practical English adult class','🗣️'],
['productive','/prəˈdʌktɪv/','productivo/a','We had a productive meeting.','Tuvimos una reunión productiva.','Work & Ability','productive team meeting adults','📈'],
['efficient','/ɪˈfɪʃənt/','eficiente','The new system is more efficient.','El sistema nuevo es más eficiente.','Work & Ability','efficient workplace system adult','⚙️'],
['successful','/səkˈsɛsfəl/','exitoso/a','The event was very successful.','El evento fue muy exitoso.','Work & Ability','successful business event adults','🏆'],
['unsuccessful','/ˌʌnsəkˈsɛsfəl/','sin éxito','Our first attempt was unsuccessful.','Nuestro primer intento no tuvo éxito.','Work & Ability','unsuccessful attempt work adult','📉'],
['employed','/ɪmˈplɔɪd/','empleado/a','She is currently employed full-time.','Ella actualmente está empleada a tiempo completo.','Work & Ability','employed adult office','🧑‍💼'],
['unemployed','/ˌʌnɪmˈplɔɪd/','desempleado/a','He was unemployed for two months.','Él estuvo desempleado por dos meses.','Work & Ability','unemployed adult job search','🔎'],
['independent','/ˌɪndɪˈpɛndənt/','independiente','She is an independent business owner.','Ella es una dueña de negocio independiente.','Work & Ability','independent business owner woman','🏪'],
['dependent','/dɪˈpɛndənt/','dependiente','The schedule is dependent on the weather.','El horario depende del clima.','Work & Ability','schedule dependent weather outdoor','🔗'],
['reliable','/rɪˈlaɪəbəl/','confiable','We need a reliable babysitter.','Necesitamos una niñera confiable.','Work & Ability','reliable babysitter family','🤝'],
['unreliable','/ˌʌnrɪˈlaɪəbəl/','poco confiable','The old car is unreliable.','El carro viejo es poco confiable.','Work & Ability','unreliable old car breakdown','🚙'],
['prepared','/prɪˈpɛrd/','preparado/a','The students are prepared for the test.','Los estudiantes están preparados para el examen.','Work & Ability','prepared adult students test','📚'],
['motivated','/ˈmoʊtəˌveɪtɪd/','motivado/a','She is motivated to learn English.','Ella está motivada para aprender inglés.','Work & Ability','motivated adult English learner','🚀'],

// General descriptions (181–200)
['popular','/ˈpɑpjələr/','popular','This is a popular restaurant.','Este es un restaurante popular.','General Description','popular restaurant adults','⭐'],
['common','/ˈkɑmən/','común','That is a common mistake.','Ese es un error común.','General Description','common English mistake class','🔁'],
['different','/ˈdɪfərənt/','diferente','My new schedule is different.','Mi horario nuevo es diferente.','General Description','different schedules comparison','↔️'],
['similar','/ˈsɪmələr/','similar','The two phones look similar.','Los dos teléfonos se ven similares.','General Description','similar smartphones comparison','🟰'],
['special','/ˈspɛʃəl/','especial','Today is a special day.','Hoy es un día especial.','General Description','special day family celebration','🎉'],
['normal','/ˈnɔrməl/','normal','A little stress is normal.','Un poco de estrés es normal.','General Description','normal daily stress adult','🙂'],
['strange','/streɪndʒ/','extraño/a','I heard a strange noise.','Escuché un ruido extraño.','General Description','strange noise adult home','👀'],
['local','/ˈloʊkəl/','local','We support local businesses.','Apoyamos a los negocios locales.','General Description','local small business adults','📍'],
['public','/ˈpʌblɪk/','público/a','The public library closes at eight.','La biblioteca pública cierra a las ocho.','General Description','public library adults','🏛️'],
['private','/ˈpraɪvət/','privado/a','This is a private conversation.','Esta es una conversación privada.','General Description','private conversation adults','🔏'],
['personal','/ˈpɜrsənəl/','personal','Do not share personal information.','No compartas información personal.','General Description','personal information online safety','👤'],
['social','/ˈsoʊʃəl/','social','The class includes social activities.','La clase incluye actividades sociales.','General Description','social activity adult class','👥'],
['legal','/ˈliɡəl/','legal','You may need legal advice.','Quizás necesites asesoría legal.','General Description','legal advice adult lawyer','⚖️'],
['illegal','/ɪˈliɡəl/','ilegal','It is illegal to drive without a license.','Es ilegal conducir sin licencia.','General Description','illegal driving without license','🚫'],
['fair','/fɛr/','justo/a','The manager made a fair decision.','El gerente tomó una decisión justa.','General Description','fair decision workplace adults','⚖️'],
['unfair','/ʌnˈfɛr/','injusto/a','The new rule seems unfair.','La regla nueva parece injusta.','General Description','unfair rule employee discussion','👎'],
['true','/tru/','verdadero/a','The story is true.','La historia es verdadera.','General Description','true story adults talking','✅'],
['false','/fɔls/','falso/a','The website displayed false information.','El sitio web mostró información falsa.','General Description','false information website laptop','❌'],
['real','/ril/','real','Is that a real diamond?','¿Ese es un diamante real?','General Description','real diamond inspection','💎'],
['main','/meɪn/','principal','The main entrance is on the left.','La entrada principal está a la izquierda.','General Description','main entrance building adults','🚪']
];
window.ADJECTIVES=rows.map(([word,ipa,es,example,exampleEs,category,image,icon])=>({word,ipa,es,example,exampleEs,category,image,icon}));
})();
